version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: all-contributors-cli
    versions:
    - 6.19.0
  - dependency-name: jest
    versions:
    - 26.0.1
